name: Build and Deploy
on: 
  push:
      branches:
        - main #push到哪个分支时触发自动部署，推荐main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Node            # 安装 Node 环境
      uses: actions/setup-node@v1
      with:
        node-version: "12.3.0"
    - name: Hexo Generate         # 安装 Hexo 依赖并且生成静态文件
      run: |
        npm i
        npm i hexo-renderer-swig
        cd themes/sagiri/
        npm i && npm install --save nprogress
        cd ../../
        npm run clean
        npm run build

    - name: Hexo Deploy           # 部署步骤，这里以 hexo deploy 为例
      env:
        SSH_PRIVATE: ${{ secrets.HEXO_DEPLOY_KEY }}
        GIT_NAME: SmallKunKun
        GIT_EMAIL: 1764746475@qq.com
      run: |
        mkdir -p ~/.ssh/
        echo "$HEXO_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name "$GIT_NAME"
        git config --global user.email "$GIT_EMAIL"
        npm run deploy
